
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 3;
  public static final int MULT = 29;
  public static final int CHAR = 11;
  public static final int PUNTO_Y_COMA = 7;
  public static final int DOUBLE = 10;
  public static final int RESTA = 28;
  public static final int DOS_PUNTOS = 9;
  public static final int CLOSEPAREN = 22;
  public static final int IDENTIFICADOR = 2;
  public static final int IGUAL = 23;
  public static final int OPENPAREN = 21;
  public static final int COLUMN = 26;
  public static final int ARROBA = 17;
  public static final int DIV = 30;
  public static final int SUMA = 27;
  public static final int MIN = 37;
  public static final int MEDIANA = 33;
  public static final int EOF = 0;
  public static final int DECIMAL = 5;
  public static final int error = 1;
  public static final int PROGRAM = 12;
  public static final int COMA = 16;
  public static final int CADENA = 4;
  public static final int MODA = 34;
  public static final int MOD = 31;
  public static final int ASIGNACION = 14;
  public static final int PUNTOS = 8;
  public static final int ACCESO = 15;
  public static final int VARIANZA = 35;
  public static final int END = 13;
  public static final int ARR = 18;
  public static final int MEDIA = 32;
  public static final int CLOSECORCHETE = 20;
  public static final int OPENCORCHETE = 19;
  public static final int MAX = 36;
  public static final int VAR = 6;
  public static final int PRINT = 25;
  public static final int CONSOLE = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFICADOR",
  "NUMERO",
  "CADENA",
  "DECIMAL",
  "VAR",
  "PUNTO_Y_COMA",
  "PUNTOS",
  "DOS_PUNTOS",
  "DOUBLE",
  "CHAR",
  "PROGRAM",
  "END",
  "ASIGNACION",
  "ACCESO",
  "COMA",
  "ARROBA",
  "ARR",
  "OPENCORCHETE",
  "CLOSECORCHETE",
  "OPENPAREN",
  "CLOSEPAREN",
  "IGUAL",
  "CONSOLE",
  "PRINT",
  "COLUMN",
  "SUMA",
  "RESTA",
  "MULT",
  "DIV",
  "MOD",
  "MEDIA",
  "MEDIANA",
  "MODA",
  "VARIANZA",
  "MAX",
  "MIN"
  };
}

