
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 3;
  public static final int MULT = 27;
  public static final int PUNTO_Y_COMA = 7;
  public static final int GLINE = 38;
  public static final int RESTA = 26;
  public static final int DOS_PUNTOS = 9;
  public static final int CLOSEPAREN = 20;
  public static final int TITULOY = 44;
  public static final int TITULOX = 43;
  public static final int EJEY = 42;
  public static final int IDENTIFICADOR = 2;
  public static final int EJEX = 41;
  public static final int IGUAL = 21;
  public static final int OPENPAREN = 19;
  public static final int GPIE = 37;
  public static final int COLUMN = 24;
  public static final int ARROBA = 15;
  public static final int TITULO = 40;
  public static final int DIV = 28;
  public static final int SUMA = 25;
  public static final int GBAR = 36;
  public static final int MIN = 35;
  public static final int MEDIANA = 31;
  public static final int EOF = 0;
  public static final int DECIMAL = 5;
  public static final int error = 1;
  public static final int PROGRAM = 10;
  public static final int COMA = 14;
  public static final int CADENA = 4;
  public static final int VALUES = 45;
  public static final int MODA = 32;
  public static final int MOD = 29;
  public static final int ASIGNACION = 12;
  public static final int PUNTOS = 8;
  public static final int GHISTOGRAM = 39;
  public static final int ACCESO = 13;
  public static final int VARIANZA = 33;
  public static final int END = 11;
  public static final int ARR = 16;
  public static final int MEDIA = 30;
  public static final int CLOSECORCHETE = 18;
  public static final int OPENCORCHETE = 17;
  public static final int EXEC = 47;
  public static final int LABEL = 46;
  public static final int MAX = 34;
  public static final int VAR = 6;
  public static final int PRINT = 23;
  public static final int CONSOLE = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFICADOR",
  "NUMERO",
  "CADENA",
  "DECIMAL",
  "VAR",
  "PUNTO_Y_COMA",
  "PUNTOS",
  "DOS_PUNTOS",
  "PROGRAM",
  "END",
  "ASIGNACION",
  "ACCESO",
  "COMA",
  "ARROBA",
  "ARR",
  "OPENCORCHETE",
  "CLOSECORCHETE",
  "OPENPAREN",
  "CLOSEPAREN",
  "IGUAL",
  "CONSOLE",
  "PRINT",
  "COLUMN",
  "SUMA",
  "RESTA",
  "MULT",
  "DIV",
  "MOD",
  "MEDIA",
  "MEDIANA",
  "MODA",
  "VARIANZA",
  "MAX",
  "MIN",
  "GBAR",
  "GPIE",
  "GLINE",
  "GHISTOGRAM",
  "TITULO",
  "EJEX",
  "EJEY",
  "TITULOX",
  "TITULOY",
  "VALUES",
  "LABEL",
  "EXEC"
  };
}

