
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CADENA = 4;
  public static final int CHAR = 11;
  public static final int DECIMAL = 5;
  public static final int END = 13;
  public static final int PUNTOS = 8;
  public static final int OPENCOMENT = 16;
  public static final int PROGRAM = 12;
  public static final int DOS_PUNTOS = 9;
  public static final int ASIGNACION = 14;
  public static final int EOF = 0;
  public static final int EXCLAMACION = 15;
  public static final int error = 1;
  public static final int NUMERO = 3;
  public static final int IDENTIFICADOR = 2;
  public static final int SALTO = 18;
  public static final int VAR = 6;
  public static final int PUNTO_Y_COMA = 7;
  public static final int CLOSECOMENT = 17;
  public static final int DOUBLE = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFICADOR",
  "NUMERO",
  "CADENA",
  "DECIMAL",
  "VAR",
  "PUNTO_Y_COMA",
  "PUNTOS",
  "DOS_PUNTOS",
  "DOUBLE",
  "CHAR",
  "PROGRAM",
  "END",
  "ASIGNACION",
  "EXCLAMACION",
  "OPENCOMENT",
  "CLOSECOMENT",
  "SALTO"
  };
}

